#!/bin/bash

## Copyright (c) 2022, Lancaster University
## All rights reserved.
##
## Redistribution and use in source and binary forms, with or without
## modification, are permitted provided that the following conditions
## are met:
##
## 1. Redistributions of source code must retain the above copyright
##    notice, this list of conditions and the following disclaimer.
##
## 2. Redistributions in binary form must reproduce the above
##    copyright notice, this list of conditions and the following
##    disclaimer in the documentation and/or other materials provided
##    with the distribution.
##
## 3. Neither the name of the copyright holder nor the names of its
##    contributors may be used to endorse or promote products derived
##    from this software without specific prior written permission.
##
## THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS
## "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT
## LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS
## FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE
## COPYRIGHT HOLDER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT,
## INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES
## (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR
## SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION)
## HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT,
## STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE)
## ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED
## OF THE POSSIBILITY OF SUCH DAMAGE.

RHOST="$HOSTNAME"
while [ $# -gt 0 ] ; do
    arg="$1" ; shift
    case "$arg" in
	(--name=*)
	    SERVER="${arg#*=}"
	    ;;

	(--connect=*)
	    if [[ "${arg#*=}" =~ ^([^:]+)(:([0-9]+))?$ ]] ; then
		RHOST="${BASH_REMATCH[1]}"
		RPORT="${BASH_REMATCH[3]}"
	    else
		printf >&2 '%s: bad connect address: %s\n' "$0" "${arg#*=}"
		exit 1
	    fi
	    ;;

	(--no-name)
	    unset SERVER
	    ;;

	(-*)
	    printf >&2 '%s: unknown switch %s\n' "$0" "$arg"
	    exit 1
	    ;;

	(*)
	    printf >&2 '%s: unknown argument %s\n' "$0" "$arg"
	    exit 1
	    ;;
    esac
done

ARGS=()
ARGS+=( -connect "$RHOST"${RPORT:+:"$RPORT"} )
ARGS+=( -servername "${SERVER:-"${RHOST}"}" )
# declare -p ARGS

DATETXT="$(true | openssl s_client "${ARGS[@]}" 2> /dev/null | \
openssl x509 -noout -dates | grep notAfter | cut -d= -f2)"
if [ -z "$DATETXT" ] ; then exit 1 ; fi
date '+%s' -d "$DATETXT"
