#!/bin/bash
# -*- c-basic-offset: 4; indent-tabs-mode: nil -*-

## Copyright (c) 2022, Lancaster University
## All rights reserved.
##
## Redistribution and use in source and binary forms, with or without
## modification, are permitted provided that the following conditions
## are met:
##
## 1. Redistributions of source code must retain the above copyright
##    notice, this list of conditions and the following disclaimer.
##
## 2. Redistributions in binary form must reproduce the above
##    copyright notice, this list of conditions and the following
##    disclaimer in the documentation and/or other materials provided
##    with the distribution.
##
## 3. Neither the name of the copyright holder nor the names of its
##    contributors may be used to endorse or promote products derived
##    from this software without specific prior written permission.
##
## THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS
## "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT
## LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS
## FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE
## COPYRIGHT HOLDER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT,
## INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES
## (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR
## SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION)
## HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT,
## STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE)
## ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED
## OF THE POSSIBILITY OF SUCH DAMAGE.


while [ $# -gt 0 ] ; do
    arg="$1" ; shift

    case "$arg" in
        (+o)
            unset OUTPUT
            ;;

        (-o)
            OUTPUT="$1" ; shift
            ;;

        (-*|+*)
            printf >&2 '%s: unknown switch %s\n' "$0" "$arg"
            exit 1
            ;;

        (*)
            INPUTS+=("$arg")
            ;;
    esac
done

function parse_attrs () {
    ## First word is the node, used to index other data.
    local key="$1" ; shift
    NODES["$key"]=yes

    while [ $# -gt 0 ] ; do
        local arg="$1" ; shift
        local value="${arg#*=}"
        if [ "$value" = "$arg" ] ; then
            printf >&2 'Value %q discarded for %q\n' "$value" "$key"
        else
            local name="${arg%"=$value"}"
            case "$name" in
                (addrs)
                    ADDRS["$key"]="$value"
                    ;;

                (func)
                    ## TODO: Drop func.
                    FUNC["$key"]="$value"
                    ;;

                (xroots)
                    XROOTS["$key"]="$value"
                    ;;

                (building)
                    BUILDING["$key"]="$value"
                    ;;

                (room)
                    ROOM["$key"]="$value"
                    ;;

                (cabinet|rack)
                    CABINET["$key"]="$value"
                    ;;

                (level)
                    LEVEL["$key"]="$value"
                    ;;

                (roles)
                    ROLES["$key"]="$value"
                    ;;

                (osds)
                    OSDS["$key"]="$value"
                    ;;

                (*)
                    printf >&2 'Unknown attr %q with value %q for %q\n' \
                               "$name" "$value" "$key"
                    ;;
            esac
        fi
    done

    ## Map addresses back to the node.
    if [ -n "${ADDRS["$key"]}" ] ; then
        local hosts=()
        IFS=',' read -ra hosts <<< "${ADDRS["$key"]}" ; shift
        for host in "${hosts[@]}" ; do
            NODE["$host"]="$key"
        done
    fi

    ## Map xroots back to the node.
    if [ -n "${XROOTS["$key"]}" ] ; then
        local hosts=()
        IFS=',' read -ra hosts <<< "${XROOTS["$key"]}" ; shift
        for host in "${hosts[@]}" ; do
            XROOTNODE["$host"]="$key"
        done
    fi
}


## Parse inputs and build up data.
declare -A FUNC
declare -A XROOTS XROOTNODE NODES
declare -A NODE ADDRS PING UP BUILDING ROOM CABINET LEVEL ROLES OSDS
for input in "${INPUTS[@]}" ; do
    while read -a words ; do
        if [ -z "${words[0]}" ] ; then continue ; fi
        if [ "${words[0]:0:1}" = '#' ] ; then continue ; fi
        parse_attrs "${words[@]}"
    done < "$input"
done

## Get RTTs for each address
for host in "${!NODE[@]}" ; do
    readarray -t lines < <(ping -c 1 -w 1 "$host" 2> /dev/null)
    last="${lines[${#lines[@]}-1]}"
    if [[ "$last" =~ ^rtt\ min/avg/max/mdev\ =\ ([^/]+)/ ]] ; then
        PING["$host"]="${BASH_REMATCH[1]}"
        UP["$host"]=1
    else
        UP["$host"]=0
    fi
done

function doit () {
    ## XRootD metrics are just an expectation of existence.  name and
    ## host are key fields.
    printf '# HELP xrootd_expect metadata for a XRootD server existing\n'
    for xrootd in "${!XROOTNODE[@]}" ; do
        if [[ "$xrootd" =~ ^([^@]*)@(.*)$ ]] ; then
            printf 'xrootd_expect{name="%s",host="%s",node="%s"} 1\n' \
                   "${BASH_REMATCH[1]}" "${BASH_REMATCH[2]}" \
                   "${XROOTNODE["$xrootd"]}"
        fi
    done

    ## IP metrics are essentially just RTTs.  iface is the key
    ## field.  TODO: Drop exported_instance.

    printf '# HELP ip_up whether a host is reachable\n'
    printf '# TYPE ip_up gauge\n'
    for host in "${!NODE[@]}" ; do
        printf 'ip_up{iface="%s"' "$host"

        ## TODO: Disable exported_instance.
        printf ',exported_instance="%s"' "${NODE["$host"]}"

        printf '} %d\n' "${UP["$host"]}"
    done

    printf '# HELP ip_ping RTT to IP in ms\n'
    printf '# TYPE ip_ping gauge\n'
    for host in "${!PING[@]}" ; do
        printf 'ip_ping{iface="%s"' "$host"

        ## TODO: Disable exported_instance.
        printf ',exported_instance="%s"' "${NODE["$host"]}"

        printf '} %.3f\n' "${PING["$host"]}"
    done

    printf '# HELP ip_metadata extra info about an IP address\n'
    for host in "${!NODE[@]}" ; do
        printf 'ip_metadata{iface="%s",node="%s"' "$host" "${NODE["$host"]}"

        ## TODO: Disable these labels.
        node="${NODE["$host"]}"
        printf ',exported_instance="%s"' "$node"
        printf ',hostname="%s"' "$host"
        if [ "${FUNC["$node"]}" ] ; then
            printf ',func="%s"' "${FUNC["$node"]}"
        fi
        if [ "${BUILDING["$node"]}" ] ; then
            printf ',building="%s"' "${BUILDING["$node"]}"
        fi
        if [ "${ROOM["$node"]}" ] ; then
            printf ',room="%s"' "${ROOM["$node"]}"
        fi
        if [ "${CABINET["$node"]}" ] ; then
            printf ',rack="%s"' "${CABINET["$node"]}"
        fi
        if [ "${LEVEL["$node"]}" ] ; then
            printf ',level="%s"' "${LEVEL["$node"]}"
        fi
        rolewords=(${ROLES["$node"]//,/ })
        declare -A roles=()
        for role in "${rolewords[@]}" ; do
            roles["$role"]=yes
        done
        for role in "${!roles[@]}" ; do
            printf ',role_%s="yes"' "$role"
        done
        if [ "${#roles[@]}" -gt 0 ] ; then
            printf ',roles="/'
            printf '%s/' "${!roles[@]}"
            printf '"'
        fi

        printf '} 1\n'
    done

    ## Machine metrics are about a physical or virtual machine,
    ## regardless of how many interfaces it's got.  node is the key
    ## field.  TODO: Drop exported_instance.

    printf '# HELP machine_osd_drives how many drives are allocated as OSDs\n'
    printf '# TYPE machine_osd_drives gauge\n'
    for node in "${!OSDS[@]}" ; do
        printf 'machine_osd_drives{node="%s",exported_instance="%s"} %d\n' \
               "$node" "$node" "${OSDS["$node"]}"
    done

    if true ; then
        printf '# HELP ip_osd_drives how many drives are allocated as OSDs (deprecated)\n'
        printf '# TYPE ip_osd_drives gauge\n'
        for node in "${!OSDS[@]}" ; do
            printf 'ip_osd_drives{exported_instance="%s"} %d\n' \
                   "$node" "${OSDS["$node"]}"
        done
    fi

    printf '# HELP machine_location physical location of a machine\n'
    for node in "${!NODES[@]}" ; do
        printf 'machine_location{node="%s",exported_instance="%s"' \
               "$node" "$node"
        if [ "${BUILDING["$node"]}" ] ; then
            printf ',building="%s"' "${BUILDING["$node"]}"
        fi
        if [ "${ROOM["$node"]}" ] ; then
            printf ',room="%s"' "${ROOM["$node"]}"
        fi
        if [ "${CABINET["$node"]}" ] ; then
            printf ',rack="%s"' "${CABINET["$node"]}"
        fi
        if [ "${LEVEL["$node"]}" ] ; then
            printf ',level="%s"' "${LEVEL["$node"]}"
        fi

        printf '} 1\n'
    done

    printf '# HELP machine_role a purpose of a machine\n'
    for node in "${!NODES[@]}" ; do
        ## Convert the comma-separated roles into a word list.
        rolewords=(${ROLES["$node"]//,/ })
        declare -A roles=()
        for role in "${rolewords[@]}" ; do
            roles["$role"]=yes
        done

        for role in "${!roles[@]}" ; do
            printf \
                'machine_role{node="%s",role="%s",exported_instance="%s"} 1\n' \
                "$node" "$role" "$node"
        done
    done

    printf '# HELP machine_roles all purposes of a machine\n'
    for node in "${!NODES[@]}" ; do
        ## Convert the comma-separated roles into a word list.
        rolewords=(${ROLES["$node"]//,/ })
        declare -A roles=()
        for role in "${rolewords[@]}" ; do
            roles["$role"]=yes
        done

        if [ "${#roles[@]}" -gt 0 ] ; then
            printf \
                'machine_roles{node="%s",exported_instance="%s",roles="/' \
                "$node" "$node"
            printf '%s/' "${!roles[@]}"
            printf '"} 1\n'
        fi
    done
}

if [ "$OUTPUT" -a "$OUTPUT" != '-' ] ; then
    OUTPUT="$(realpath -m "$OUTPUT")"
    tmp="${OUTPUT%/*}/.${OUTPUT##*/}.tmp"
    if touch "$tmp" ; then
        doit > "$tmp"
        mv "$tmp" "$OUTPUT"
    fi
else
    doit
fi
